<html>
    <head>
        <link href="<?php echo APP_URL;?>/css/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo APP_URL;?>/css/main.css" rel="stylesheet" type="text/css">
        <link href="<?php echo APP_URL;?>/plugins/select2/select2.css" rel="stylesheet" type="text/css">
        <link href="<?php echo APP_URL;?>/plugins/parsley/parsley.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <header>
            
        </header>
        <div id="content">
            <?php echo $this->layout()->content ?>
        </div>
        <footer>
            <script src="<?php echo APP_URL;?>/plugins/jquery/jquery-1.11.1.min.js"></script>
            <script src="<?php echo APP_URL;?>/css/bootstrap/js/bootstrap.min.js"></script>
            <script src="<?php echo APP_URL;?>/plugins/select2/select2.js"></script>
            <script src="<?php echo APP_URL;?>/plugins/parsley/parsley.js"></script>
            <script src="<?php echo APP_URL;?>/js/main.js"></script>
        </footer>
    </body>
</html>